package models

type Mb struct {
	Id                      int     `orm:"id"`
	CreateDate              string  `orm:"create_date"`
	ModifyDate              string  `orm:"modify_date"`
	AcceptBindDate          string  `orm:"accept_bind_date"`
	Attendance              int     `orm:"attendance"`
	Bind                    int     `orm:"bind"`
	BindOpenid              string  `orm:"bind_openid"`
	DeleteFlag              int     `orm:"delete_flag"`
	Duties                  int     `orm:"duties"`
	FaceImageUrl            string  `orm:"face_image_url"`
	HeadImage               string  `orm:"head_image"`
	IdCardfmurl             string  `orm:"id_cardfmurl"`
	IdCardzmurl             string  `orm:"id_cardzmurl"`
	IdNo                    string  `orm:"id_no"`
	MemberType              int     `orm:"member_type"`
	Mobile                  string  `orm:"mobile"`
	Money                   float64 `orm:"money"`
	Nickname                string  `orm:"nickname"`
	WorkerType              string  `orm:"worker_type"`
	WorkingState            int     `orm:"working_state"`
	WorkingStateApproveDate string  `orm:"working_state_approve_date"`
	Admin                   int     `orm:"admin"`
	AdminProject            int     `orm:"admin_project"`
	MemberGroup             int     `orm:"member_group"`
	Signature               string  `orm:"signature"`
	Unionid                 string  `orm:"unionid"`
	Clouduid                string  `orm:"clouduid"`
	Feature                 string  `orm:"feature"`
}

type Ma struct {
	Id                        int     `orm:"id"`
	CreateDate                string  `orm:"create_date"`
	ModifyDate                string  `orm:"modify_date"`
	BindOpenid                string  `orm:"bind_openid"`
	Birthday                  string  `orm:"birthday"`
	DeleteFlag                int     `orm:"delete_flag"`
	HeadImage                 string  `orm:"head_image"`
	InvitationCode            string  `orm:"invitation_code"`
	LoginDate                 string  `orm:"login_date"`
	Mobile                    string  `orm:"mobile"`
	Money                     float64 `orm:"money"`
	MyinvitationCode          string  `orm:"myinvitation_code"`
	Nickname                  string  `orm:"nickname"`
	Password                  string  `orm:"password"`
	Score                     int     `orm:"score"`
	CompanyName               string  `orm:"company_name"`
	ActivateProlocutor        int     `orm:"activate_prolocutor"`
	MemberType                int     `orm:"member_type"`
	Point                     float64 `orm:"point"`
	RequireType               int     `orm:"require_type"`
	CustomPoint               float64 `orm:"custom_point"`
	PopularizeMember          int     `orm:"popularize_member"`
	WxQrCodeUrl               string  `orm:"wx_qr_code_url"`
	Address                   string  `orm:"address"`
	Telephone                 string  `orm:"telephone"`
	TopContacts               string  `orm:"top_contacts"`
	Department                string  `orm:"department"`
	Admin                     int     `orm:"admin"`
	JobNumber                 string  `orm:"job_number"`
	Bind                      int     `orm:"bind"`
	Sources                   string  `orm:"sources"`
	Textarea                  string  `orm:"textarea"`
	ExtendFields              string  `orm:"extend_fields"`
	Attendance                int     `orm:"attendance"`
	IdNo                      string  `orm:"id_no"`
	WorkerType                string  `orm:"worker_type"`
	FaceImageUrl              string  `orm:"face_image_url"`
	WorkerPlatformReceiveFlag int     `orm:"worker_platform_receive_flag"`
	Locations                 string  `orm:"locations"`
	IdCardfmurl               string  `orm:"id_cardfmurl"`
	IdCardRecognition         string  `orm:"id_card_recognition"`
	IdCardzmurl               string  `orm:"id_cardzmurl"`
	HoursPerDay               int     `orm:"hours_per_day"`
	Remarks                   string  `orm:"remarks"`
	WorkingState              int     `orm:"working_state"`
	WorkingStateApproveDate   string  `orm:"working_state_approve_date"`
	Duties                    int     `orm:"duties"`
	MemberGroup               int     `orm:"member_group"`
	MemberGroupId             int     `orm:"member_group_id"`
	FaceInfo                  string  `orm:"face_info"`
	AcceptBindDate            string  `orm:"accept_bind_date"`
}
